name: wevote

services:
  webapp:
    build:
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:3000:3000" # this allows access to the WeVote WebApp at localhost:3000  
    networks:
      - wevote

networks:
  wevote:
    name: wevote
    external: true
