version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 25
  build:
    on-failure: ABORT
    commands:
      - echo "Installing dependencies"
      - npm install
      - echo "Running Browserstack tests"
      - npm run wdio-BVT
