import webAppConfig from '../../config';

if (window.cordova) { // Static constants are initialized before the app starts
  webAppConfig.IS_CORDOVA = true;
  window.isCordovaGlobal = true;
}

// eslint-disable-next-line import/prefer-default-export
export const officialWebsites = [
  'https://aldemocrats.org/2026-qualified-candidates',
  'https://algop.org/qualified-2026-republican-candidates/',
  'https://www.elections.alaska.gov/',
  'https://apps.arizona.vote/electioninfo/Election/68',
  'https://candidates.arkansas.gov/',
  'http://elections.cdn.sos.ca.gov/statewide-elections/2026-primary/contact-list.pdf',
  'https://www.coloradosos.gov/pubs/elections/vote/primaryCandidates.html',
  'https://portal.ct.gov/sots/election-services/town-ballots/ballots',
  'https://efiling.ocf.dc.gov/ActiveCandidates',
  'https://dos.elections.myflorida.com/candidates/index.asp',
  'https://mvp.sos.ga.gov/s/',
  'https://olvr.hawaii.gov/Controls/CandidateFiling.aspx?elid=92',
  'https://run.voteidaho.gov/search',
  'https://www.elections.il.gov/ElectionOperations/CandidatesFiled.aspx',
  'https://indianacitizen.org/2026-indiana-primary-candidate-list/',
  'https://sos.iowa.gov/voters/candidates',
  'https://sos.ks.gov/elections/elections_upcoming_candidate.aspx',
  'https://web.sos.ky.gov/CandidateFilings/',
  'https://voterportal.sos.la.gov/CandidateInquiry',
  'https://www.maine.gov/sos/elections-voting/upcoming-elections',
  'https://www.sec.state.ma.us/divisions/elections/elections-and-voting.htm',
  'https://www.michigan.gov/sos/elections/election-results-and-data',
  'https://www.sos.mo.gov/elections',
  'https://candidates.sos.mn.gov/',
  'https://www.sos.ms.gov/node/1825',
  'https://sosmt.gov/elections/filing/',
  'https://sos.nebraska.gov/elections',
  'https://www.nvsos.gov/SOSCandidateServices/AnonymousAccess/CEFDSearchUU/CertCandList.aspx',
  'https://www.sos.nh.gov/2026-election-details',
  'https://nj.gov/state/elections/election-chronological-timelines.shtml',
  'https://candidateportal.servis.sos.state.nm.us/CandidateList.aspx?eid=2911&cty=99',
  'https://publicreporting.elections.ny.gov/',
  'https://www.ncsbe.gov/results-data/candidate-lists',
  'https://vip.sos.nd.gov/candidatelist.aspx?eid=346',
  'https://www.ohiosos.gov/directories/county-boards-of-elections',
  'https://oklahoma.gov/elections.html',
  'https://secure.sos.state.or.us/orestar/CFSearchPage.do',
  'https://vote.phila.gov/voting/candidates-for-office/',
  'https://vote.sos.ri.gov/Candidates/CandidateSearch',
  'https://vrems.scvotes.sc.gov/Candidate/SelectElection',
  'https://sdsos.gov/elections-voting/',
  'https://sos.tn.gov/elections/2026-candidate-lists',
  'https://goelect.txelections.civixapps.com/ivis-cbp-ui/candidate-information',
  'https://vote.utah.gov/2026-candidate-filings/',
  'https://sos.vermont.gov/elections/election-info-resources/candidates',
  'https://www.elections.virginia.gov/casting-a-ballot/candidate-list/',
  'https://voter.votewa.gov/CandidateList.aspx?e=898',
  'https://candidates.wvsos.gov/',
  'https://elections.wi.gov/elections',
  'https://sos.wyo.gov/Elections/2026ElectionInformation.aspx',
];
