const browserStackConfig = require('./browserstack.config');

const date = new Date();
const dateForDisplay = date.toDateString();
const buildNameForDisplay = `${browserStackConfig.BUILD}: ${dateForDisplay}`;

exports.config = {
  user: browserStackConfig.BROWSERSTACK_USER,
  key: browserStackConfig.BROWSERSTACK_KEY,
  webAppRootUrl: browserStackConfig.WEB_APP_ROOT_URL,
  updateJob: false,
  specs: [
    './tests/browserstack/specs/ballotMainTest.js',
  ],
  twitterUserName: browserStackConfig.TWITTER_USER_NAME,
  twitterPassword: browserStackConfig.TWITTER_PASSWORD,
  exclude: [],
  capabilities: [
    {
      name: 'ballotMainTest-AndroidSamsungGalaxyS9PlusAndroid',
      build: buildNameForDisplay,
      device: 'Samsung Galaxy S9 Plus',
      os: '',
      os_version: '8.0',
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: false,
      isIOS: false,
      isMobileScreenSize: true,
    },
    {
      name: 'ballotMainTest-AndroidSamsungGalaxyJ7PrimeAndroid',
      build: buildNameForDisplay,
      device: 'Samsung Galaxy J7 Prime',
      os: '',
      os_version: '8.1',
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: false,
      isIOS: false,
      isMobileScreenSize: true,
    },
    {
      name: 'ballotMainTest-AndroidSamsungGalaxyS8Android',
      build: buildNameForDisplay,
      device: 'Samsung Galaxy S8',
      os: '',
      os_version: '7.0',
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: false,
      isIOS: false,
      isMobileScreenSize: true,
    },
    {
      name: 'ballotMainTest-AndroidGooglePixel4Android',
      build: buildNameForDisplay,
      device: 'Google Pixel 4',
      os: '',
      os_version: '10.0',
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: false,
      isIOS: false,
      isMobileScreenSize: true,
    },
    {
      name: 'ballotMainTest-AndroidGooglePixel3Android',
      build: buildNameForDisplay,
      device: 'Google Pixel 3',
      os: '',
      os_version: '10.0',
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: false,
      isIOS: false,
      isMobileScreenSize: true,
    },
  ],
  waitforTimeout: 180000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 360000,
  },
}
