#!/bin/bash
usage () { echo -e "Usage: $0 -f <path to configuration file> -o <os_version> [-w <file to write>] [-d <device name>] [-b <browser>] [-c <console>] [-l (local)] [-u (updateJob)] [--os <os>] [--debug] [--ssl] [--loglevel <log level>] [--ios] [--android] [--cordova] [--mobile-screen] [--real-mobile] [--colored-logs] [--wait-for-timeout <length>] [--connection-retry-timeout <length>] [--connection-retry-count <count>]\n\nExample: $0 -f /opt/MyProjects/WebApp/tests/browserstack/test.wdio.conf.js -o 10.0 --os Windows"; exit; }
error () { echo $1; exit; }

[[ $# -lt 4 ]] && usage

# Option Strings
SHORT=f:o:d:b:c:hw:lu
LONG=os:,debug,ssl,localtest,ios,android,cordova,mobile-screen,real-mobile,loglevel:,colored-logs,wait-for-timeout:,connection-retry-timeout:,connection-retry-count:

# Read the options
OPTS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
[ $? -ne 0 ] && error 'Failed to parse options.' >&2 
eval set -- "$OPTS"

# Set initial values
var_device=''
var_browser=''
var_console='errors'
var_os=''
var_real_mobile=false
var_isAndroid=false
var_isCordova=false
var_isIOS=false
var_isMobileScreenSize=false
var_debug=false
var_ssl=false
var_log_level=trace
var_localTest=false
var_updateJob=false
var_colored_logs=false
var_wait_timeout=180000
var_connection_retry_timeout=90000
var_connection_retry_count=3

# Extract options 
while true; do 
    case "$1" in 
        -f)
            filepath="$2"
            shift 2;;
        -o)
            var_OS_VERSION="$2" 
            shift 2;;
        -d)
            var_device="$2"
            shift 2;;
        -b)
            var_browser="$2"
            shift 2;;
        -c)
            var_console="$2"
            shift 2;;
        -w)
            write="$2"
            shift 2;;
        -l)
            var_localTest=true
            shift;;
        -u)
            var_updateJob=true
            shift;;
        --os)
            var_os="$2"
            shift 2;;
        --debug)
            var_debug=true
            shift;;
        --ssl)
            var_ssl=true
            shift;;
        --ios)
            var_isIOS=true
            shift;;
        --android)
            var_isAndroid=true
            shift;;
        --cordova)
            var_isCordova=true
            shift;;
        --mobile-screen)
            var_isMobileScreenSize=true
            shift;;
        --real-mobile)
            var_real_mobile=true
            shift;;
        --loglevel)
            var_log_level="$2"
            shift 2;;
        --colored-logs)
            var_colored_logs=true
            shift;;
        --wait-for-timeout)
            var_wait_timeout=$2
            shift 2;;
        --connection-retry-timeout)
            var_connection_retry_timeout=$2
            shift 2;;
        --connection-retry-count)
            var_connection_retry_count=$2
            shift 2;;
        -h)
            usage;;
        --)
            shift
            break;;
        *)
            usage;;
    esac
done

[[ -z "$var_OS_VERSION" ]] && error 'Needs os version. Use -h for help'
[[ -z "$filepath" ]] && error 'Needs path to configuration file. Use -h for help'

var_name=`echo $device | tr -d ' '`;
for variable in ${!var_@}; 
do 
    [[ ! -z "$variable" ]] && var=`echo $variable | cut -c 5-` && replaceString+="s/%$var/${!variable}/g;"
done;

[[ "$write" != "" ]] && sed "$replaceString" $filepath > $write || sed "$replaceString" $filepath;
