const browserStackConfig = require('./browserstack.config');

const date = new Date();
const dateForDisplay = date.toDateString();
const buildNameForDisplay = `${browserStackConfig.BUILD}: ${dateForDisplay}`;

exports.config = {
  user: browserStackConfig.BROWSERSTACK_USER,
  key: browserStackConfig.BROWSERSTACK_KEY,
  webAppRootUrl: browserStackConfig.WEB_APP_ROOT_URL,
  updateJob: false,
  specs: [
    './tests/browserstack/specs/%scriptNameMainTest.js',
  ],
  twitterUserName: browserStackConfig.TWITTER_USER_NAME,
  twitterPassword: browserStackConfig.TWITTER_PASSWORD,
  exclude: [],
  capabilities: [
    {
      name: '%name0',
      build: buildNameForDisplay,
      device: '%device0',
      os: '%os0',
      os_version: '%os_version0',
      browserName: '%browserName0',
      browser_version: '%browser_version0',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name1',
      build: buildNameForDisplay,
      device: '%device1',
      os: '%os1',
      os_version: '%os_version1',
      browserName: '%browserName1',
      browser_version: '%browser_version1',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name2',
      build: buildNameForDisplay,
      device: '%device2',
      os: '%os2',
      os_version: '%os_version2',
      browserName: '%browserName2',
      browser_version: '%browser_version2',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name3',
      build: buildNameForDisplay,
      device: '%device3',
      os: '%os3',
      os_version: '%os_version3',
      browserName: '%browserName3',
      browser_version: '%browser_version3',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name4',
      build: buildNameForDisplay,
      device: '%device4',
      os: '%os4',
      os_version: '%os_version4',
      browserName: '%browserName4',
      browser_version: '%browser_version4',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name5',
      build: buildNameForDisplay,
      device: '%device5',
      os: '%os5',
      os_version: '%os_version5',
      browserName: '%browserName5',
      browser_version: '%browser_version5',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name6',
      build: buildNameForDisplay,
      device: '%device6',
      os: '%os6',
      os_version: '%os_version6',
      browserName: '%browserName6',
      browser_version: '%browser_version6',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name7',
      build: buildNameForDisplay,
      device: '%device7',
      os: '%os7',
      os_version: '%os_version7',
      browserName: '%browserName7',
      browser_version: '%browser_version7',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name8',
      build: buildNameForDisplay,
      device: '%device8',
      os: '%os8',
      os_version: '%os_version8',
      browserName: '%browserName8',
      browser_version: '%browser_version8',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
    {
      name: '%name9',
      build: buildNameForDisplay,
      device: '%device9',
      os: '%os9',
      os_version: '%os_version9',
      browserName: '%browserName9',
      browser_version: '%browser_version9',
      real_mobile: %real_mobile,
      acceptSslCerts: %acceptSslCerts,
      'browserstack.browserstack.debug': %browserstack.debug,
      'browserstack.local': %browserstack.local,
      isAndroid: %isAndroid,
      isCordovaFromAppStore: %isCordova,
      isIOS: %isIOS,
      isMobileScreenSize: %isMobileScreenSize,
    },
  ],
  waitforTimeout: %waitForTimeout,
  connectionRetryTimeout: %connectionRetryTimeout,
  connectionRetryCount: %connectionRetryCount,

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 180000,
  },
}
