// Can not set browser.geoLocation and browser.local simultaneously
// eslint-disable-next-line import/no-unresolved
const browserStackConfig = require('./browserstack.config');

const date = new Date();
const dateForDisplay = date.toDateString();
const buildNameForDisplay = `${browserStackConfig.BUILD}: ${dateForDisplay}`;

exports.config = {
  user: browserStackConfig.BROWSERSTACK_USER,
  key: browserStackConfig.BROWSERSTACK_KEY,
  updateJob: false,
  specs: [
    './specs/%scriptMainTest.js',
  ],
  twitterUserName: browserStackConfig.TWITTER_USER_NAME,
  twitterPassword: browserStackConfig.TWITTER_PASSWORD,
  voterDeviceId: '%cookie',
  exclude: [],
  capabilities: [
    {
      name: '%scriptMainTest: %device0%os0 %os_version0',
      build: buildNameForDisplay,
      device: '%device0',
      os: '%os0',
      os_version: '%os_version0',
      app: '%app',
      browserName: '%browserName0',
      browser_version: '%browser_version0',
      real_mobile: '%real_mobile',
      resolution: '%resolution',
      'browserstack.console': 'info',
      'browserstack.appium_version': '%browserstack.appium_version0',
      'browserstack.local': '%browserstack.local',
      isAndroid: '%isAndroid',
      isCordovaFromAppStore: '%isCordova',
      isIOS: '%isIOS',
      isMobileScreenSize: '%isMobileScreenSize',
    },
    {
      name: '%scriptMainTest: %device1%os1 %os_version1',
      build: buildNameForDisplay,
      device: '%device1',
      os: '%os1',
      os_version: '%os_version1',
      app: '%app',
      browserName: '%browserName1',
      browser_version: '%browser_version1',
      real_mobile: '%real_mobile',
      resolution: '%resolution',
      'browserstack.console': 'info',
      'browserstack.appium_version': '%browserstack.appium_version1',
      'browserstack.local': '%browserstack.local',
      isAndroid: '%isAndroid',
      isCordovaFromAppStore: '%isCordova',
      isIOS: '%isIOS',
      isMobileScreenSize: '%isMobileScreenSize',
    },
    {
      name: '%scriptMainTest: %device2%os2 %os_version2',
      build: buildNameForDisplay,
      device: '%device2',
      os: '%os2',
      os_version: '%os_version2',
      app: '%app',
      browserName: '%browserName2',
      browser_version: '%browser_version2',
      real_mobile: 'real_mobile',
      resolution: '%resolution',
      'browserstack.console': 'info',
      'browserstack.appium_version': '%browserstack.appium_version2',
      'browserstack.local': '%browserstack.local',
      isAndroid: '%isAndroid',
      isCordovaFromAppStore: '%isCordova',
      isIOS: '%isIOS',
      isMobileScreenSize: '%isMobileScreenSize',
    },
    {
      name: '%scriptMainTest: %device3%os3 %os_version3',
      build: buildNameForDisplay,
      device: '%device3',
      os: '%os3',
      os_version: '%os_version3',
      app: '%app',
      browserName: '%browserName3',
      browser_version: '%browser_version3',
      real_mobile: '%real_mobile',
      resolution: '%resolution',
      'browserstack.console': 'info',
      'browserstack.appium_version': '%browserstack.appium_version3',
      'browserstack.local': '%browserstack.local',
      isAndroid: '%isAndroid',
      isCordovaFromAppStore: '%isCordova',
      isIOS: '%isIOS',
      isMobileScreenSize: '%isMobileScreenSize',
    },
    {
      name: '%scriptMainTest: %device4%os4 %os_version4',
      build: buildNameForDisplay,
      device: '%device4',
      os: '%os4',
      os_version: '%os_version4',
      app: '%app',
      browserName: '%browserName4',
      browser_version: '%browser_version4',
      real_mobile: '%real_mobile',
      resolution: '%resolution',
      'browserstack.console': 'info',
      'browserstack.appium_version': '%browserstack.appium_version4',
      'browserstack.local': '%browserstack.local',
      isAndroid: '%isAndroid',
      isCordovaFromAppStore: '%isCordova',
      isIOS: '%isIOS',
      isMobileScreenSize: '%isMobileScreenSize',
    },
  ],
  webviewConnectTimeout: 90000,
  baseUrl: browserStackConfig.WEB_APP_ROOT_URL,
  reporters: ['concise'],

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 360000,
  },
};
