const browserStackConfig = require('./browserstack.config');

const date = new Date();
const dateForDisplay = date.toDateString();
const buildNameForDisplay = `${browserStackConfig.BUILD}: ${dateForDisplay}`;

exports.config = {
  user: browserStackConfig.BROWSERSTACK_USER,
  key: browserStackConfig.BROWSERSTACK_KEY,
  webAppRootUrl: browserStackConfig.WEB_APP_ROOT_URL,
  updateJob: false,
  specs: [
    './tests/browserstack/specs/%scriptNameMainTest.js',
  ],
  logLevel: 'trace',
  twitterUserName: browserStackConfig.TWITTER_USER_NAME,
  twitterPassword: browserStackConfig.TWITTER_PASSWORD,
  exclude: [],
  capabilities: [
    {
      name: '%name1',
      build: buildNameForDisplay,
      device: '%device1',
      os_version: '%os_version1',
      real_mobile: %real_mobile1,
      acceptSslCerts: %ssl1,
      'project': '%project1',
      browser: '%browser1',
      'browserstack.appium_version': '1.9.1',
      'browserstack.console': '%console1',
      'browserstack.debug': %debug1,
      'browserstack.local': %local1,
      isAndroid: %isAndroid1,
      isCordovaFromAppStore: %isCordova1,
      isIOS: %isIOS1,
      isMobileScreenSize: %isMobileScreen1,
    },
    {
      name: '%name2',
      build: buildNameForDisplay,
      device: '%device2',
      os_version: '%os_version2',
      real_mobile: %real_mobile2,
      acceptSslCerts: %ssl2,
      'project': '%project2',
      browser: '%browser2',
      'browserstack.appium_version': '2.9.2',
      'browserstack.console': '%console2',
      'browserstack.debug': %debug2,
      'browserstack.local': %local2,
      isAndroid: %isAndroid2,
      isCordovaFromAppStore: %isCordova2,
      isIOS: %isIOS2,
      isMobileScreenSize: %isMobileScreen2,
    },
    {
      name: '%name3',
      build: buildNameForDisplay,
      device: '%device3',
      os_version: '%os_version3',
      real_mobile: %real_mobile3,
      acceptSslCerts: %ssl3,
      'project': '%project3',
      browser: '%browser3',
      'browserstack.appium_version': '3.9.3',
      'browserstack.console': '%console3',
      'browserstack.debug': %debug3,
      'browserstack.local': %local3,
      isAndroid: %isAndroid3,
      isCordovaFromAppStore: %isCordova3,
      isIOS: %isIOS3,
      isMobileScreenSize: %isMobileScreen3,
    },
    {
      name: '%name4',
      build: buildNameForDisplay,
      device: '%device4',
      os_version: '%os_version4',
      real_mobile: %real_mobile4,
      acceptSslCerts: %ssl4,
      'project': '%project4',
      browser: '%browser4',
      'browserstack.appium_version': '4.9.4',
      'browserstack.console': '%console4',
      'browserstack.debug': %debug4,
      'browserstack.local': %local4,
      isAndroid: %isAndroid4,
      isCordovaFromAppStore: %isCordova4,
      isIOS: %isIOS4,
      isMobileScreenSize: %isMobileScreen4,
    },
    {
      name: '%name5',
      build: buildNameForDisplay,
      device: '%device5',
      os_version: '%os_version5',
      real_mobile: %real_mobile5,
      acceptSslCerts: %ssl5,
      'project': '%project5',
      browser: '%browser5',
      'browserstack.appium_version': '5.9.5',
      'browserstack.console': '%console5',
      'browserstack.debug': %debug5,
      'browserstack.local': %local5,
      isAndroid: %isAndroid5,
      isCordovaFromAppStore: %isCordova5,
      isIOS: %isIOS5,
      isMobileScreenSize: %isMobileScreen5,
    },
  ],
  coloredLogs: true,
  logLevel: 'trace',
  baseUrl: '',
  waitforTimeout: 180000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 180000,
  },
}
