const browserStackConfig = require('./browserstack.config');

const date = new Date();
const dateForDisplay = date.toDateString();
const buildNameForDisplay = `${browserStackConfig.BUILD}: ${dateForDisplay}`;

exports.config = {
  user: browserStackConfig.BROWSERSTACK_USER,
  key: browserStackConfig.BROWSERSTACK_KEY,
  updateJob: false,
  specs: [
    './tests/browserstack/specs/readyMainTest.js',
  ],
  twitterUserName: browserStackConfig.TWITTER_USER_NAME,
  twitterPassword: browserStackConfig.TWITTER_PASSWORD,
  exclude: [],
  capabilities: [
    {
      name: 'readyMainTest-iOSiPhoneXRiPhone',
      build: buildNameForDisplay,
      device: 'iPhone XR',
      os: '',
      os_version: '12',
      browserName: 'iPhone',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': true,
      isAndroid: false,
      isCordovaFromAppStore: false,
      isIOS: true,
      isMobileScreenSize: true,
    },
    {
      name: 'readyMainTest-iOSiPhone8iPhone',
      build: buildNameForDisplay,
      device: 'iPhone 8',
      os: '',
      os_version: '13',
      browserName: 'iPhone',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': true,
      isAndroid: false,
      isCordovaFromAppStore: false,
      isIOS: true,
      isMobileScreenSize: true,
    },
    {
      name: 'readyMainTest-iOSiPhone8PlusiPhone',
      build: buildNameForDisplay,
      device: 'iPhone 8 Plus',
      os: '',
      os_version: '12',
      browserName: 'iPhone',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': true,
      isAndroid: false,
      isCordovaFromAppStore: false,
      isIOS: true,
      isMobileScreenSize: true,
    },
    {
      name: 'readyMainTest-iOSiPhone6SiPhone',
      build: buildNameForDisplay,
      device: 'iPhone 6S',
      os: '',
      os_version: '12',
      browserName: 'iPhone',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': true,
      isAndroid: false,
      isCordovaFromAppStore: false,
      isIOS: true,
      isMobileScreenSize: true,
    },
    {
      name: 'readyMainTest-iOSiPad6thiPad',
      build: buildNameForDisplay,
      device: 'iPad 6th',
      os: '',
      os_version: '11',
      browserName: 'iPad',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '1.16.0',
      'browserstack.local': true,
      isAndroid: false,
      isCordovaFromAppStore: false,
      isIOS: true,
      isMobileScreenSize: true,
    },
  ],
  baseUrl: browserStackConfig.WEB_APP_ROOT_URL,
  waitforTimeout: 180000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 360000,
  },
}
