const browserStackConfig = require('./browserstack.config');

const date = new Date();
const dateForDisplay = date.toDateString();
const buildNameForDisplay = `${browserStackConfig.BUILD}: ${dateForDisplay}`;

exports.config = {
  user: browserStackConfig.BROWSERSTACK_USER,
  key: browserStackConfig.BROWSERSTACK_KEY,
  updateJob: false,
  specs: [
    './tests/browserstack/specs/readyMainTest.js',
  ],
  twitterUserName: browserStackConfig.TWITTER_USER_NAME,
  twitterPassword: browserStackConfig.TWITTER_PASSWORD,
  exclude: [],
  capabilities: [
    {
      name: 'readyMainTest-BrowserOSXSafari13.0',
      build: buildNameForDisplay,
      os: 'OS X',
      os_version: 'Catalina',
      browserName: 'Safari',
      browser_version: '13.0',
      real_mobile: false,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.debug': true,
      'browserstack.appium_version': '%browserstack.appium_version0',
      'browserstack.local': true,
      isAndroid: false,
      isCordovaFromAppStore: false,
      isIOS: false,
      isMobileScreenSize: false,
    },
//    {
//      name: 'readyMainTest-Browser%name1',
//      build: buildNameForDisplay,
//      os: '%os1',
//      os_version: '%os_version1',
//      browserName: '%browserName1',
//      browser_version: '%browser_version1',
//      real_mobile: false,
//      acceptSslCerts: true,
//      'browserstack.console': 'info',
//      'browserstack.debug': true,
//      'browserstack.appium_version': '%browserstack.appium_version1',
//      'browserstack.local': true,
//      isAndroid: false,
//      isCordovaFromAppStore: false,
//      isIOS: false,
//      isMobileScreenSize: false,
//    },
//    {
//      name: 'readyMainTest-Browser%name2',
//      build: buildNameForDisplay,
//      os: '%os2',
//      os_version: '%os_version2',
//      browserName: '%browserName2',
//      browser_version: '%browser_version2',
//      real_mobile: false,
//      acceptSslCerts: true,
//      'browserstack.console': 'info',
//      'browserstack.debug': true,
//      'browserstack.appium_version': '%browserstack.appium_version2',
//      'browserstack.local': true,
//      isAndroid: false,
//      isCordovaFromAppStore: false,
//      isIOS: false,
//      isMobileScreenSize: false,
//    },
//    {
//      name: 'readyMainTest-Browser%name3',
//      build: buildNameForDisplay,
//      os: '%os3',
//      os_version: '%os_version3',
//      browserName: '%browserName3',
//      browser_version: '%browser_version3',
//      real_mobile: false,
//      acceptSslCerts: true,
//      'browserstack.console': 'info',
//      'browserstack.debug': true,
//      'browserstack.appium_version': '%browserstack.appium_version3',
//      'browserstack.local': true,
//      isAndroid: false,
//      isCordovaFromAppStore: false,
//      isIOS: false,
//      isMobileScreenSize: false,
//    },
//    {
//      name: 'readyMainTest-Browser%name4',
//      build: buildNameForDisplay,
//      os: '%os4',
//      os_version: '%os_version4',
//      browserName: '%browserName4',
//      browser_version: '%browser_version4',
//      real_mobile: false,
//      acceptSslCerts: true,
//      'browserstack.console': 'info',
//      'browserstack.debug': true,
//      'browserstack.appium_version': '%browserstack.appium_version4',
//      'browserstack.local': true,
//      isAndroid: false,
//      isCordovaFromAppStore: false,
//      isIOS: false,
//      isMobileScreenSize: false,
//    },
  ],
  baseUrl: browserStackConfig.WEB_APP_ROOT_URL,
  waitforTimeout: 180000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 360000,
  },
}
