#!/bin/bash
error () { echo $1; exit; }
usage () { 
  echo -e "Usage: $0 -s <script> [-r remove] [-n number of tests]\n" 
  echo -e "Example: $0 -s ballot\n"; 
  echo "Make sure you are running this in the directory in which the script is located."; 
  exit
}

numTests=5

while getopts "rs:n:" opt; 
do
    case $opt in
    r)
        remove=1;;
    s)
        script=$OPTARG;;
    n)
        numTests=$OPTARG;;
    \?)
        usage;;
    esac
done

# Checks
maxTests=5
[[ -z $script ]] && usage
[[ $numTests -gt $maxTests || $numTests -lt 1 ]] && error 'Number of tests must be between 1 and 5'
[ ! -r parallel.wdio.config.js ] && error 'Parallel.wdio.config.js does not exist in the current directory'

if [[ $remove -ne 1 ]]; then
    # Comment out tests if necessary
    if [[ $numTests -ne 5 ]]; then  
        os0=`grep -n os0 parallel.wdio.config.js`
        os1=`grep -n os1 parallel.wdio.config.js`
        blockSize=$(( ${os1%%:*} - ${os0%%:*} )) 
        os4=`grep -n os4 parallel.wdio.config.js` 
        # Number of lines between os4 and {
        lineOffset=1
        numBlocks=$((maxTests - 1 - $numTests))
        comment="$((${os4%%:*} - $lineOffset - $numBlocks * $blockSize)),$((${os4%%:*} + ($blockSize - $lineOffset - 1)))s/^/\/\//"
    fi
    # Create wdio.conf.template file
    sed -e "$comment" -e "$substitute" parallel.wdio.config.js > wdio.conf.template

    # Create main script
    cp -n ./specs/exampleTest.js ./specs/${script}MainTest.js
else
    # Remove wdio.config.template file
    rm wdio.conf.template

    # Remove main script
    rm ./specs/${script}MainTest.js
fi
