const browserStackConfig = require('./browserstack.config');

const date = new Date();
const dateForDisplay = date.toDateString();
const buildNameForDisplay = `${browserStackConfig.BUILD}: ${dateForDisplay}`;

exports.config = {
  user: browserStackConfig.BROWSERSTACK_USER,
  key: browserStackConfig.BROWSERSTACK_KEY,
  updateJob: false,
  specs: [
    './specs/ballotMainTest.js',
  ],
  twitterUserName: browserStackConfig.TWITTER_USER_NAME,
  twitterPassword: browserStackConfig.TWITTER_PASSWORD,
  exclude: [],
  capabilities: [
    {
      name: 'ballotMainTest: Samsung Galaxy Tab S6',
      build: buildNameForDisplay,
      device: 'Samsung Galaxy Tab S6',
      os: '',
      os_version: '9.0',
      app: browserStackConfig.BROWSERSTACK_APK_URL,
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: true,
      isIOS: false,
      isMobileScreenSize: false,
    },
    {
      name: 'ballotMainTest: Samsung Galaxy Tab S5e',
      build: buildNameForDisplay,
      device: 'Samsung Galaxy Tab S5e',
      os: '',
      os_version: '9.0',
      app: browserStackConfig.BROWSERSTACK_APK_URL,
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: true,
      isIOS: false,
      isMobileScreenSize: false,
    },
    {
      name: 'ballotMainTest: Samsung Galaxy Tab S4',
      build: buildNameForDisplay,
      device: 'Samsung Galaxy Tab S4',
      os: '',
      os_version: '8.1',
      app: browserStackConfig.BROWSERSTACK_APK_URL,
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: true,
      isIOS: false,
      isMobileScreenSize: false,
    },
    {
      name: 'ballotMainTest: Samsung Galaxy Tab S3',
      build: buildNameForDisplay,
      device: 'Samsung Galaxy Tab S3',
      os: '',
      os_version: '8.0',
      app: browserStackConfig.BROWSERSTACK_APK_URL,
      browserName: 'Android',
      browser_version: '',
      real_mobile: true,
      acceptSslCerts: true,
      'browserstack.console': 'info',
      'browserstack.appium_version': '1.17.0',
      'browserstack.local': false,
      'browser.geoLocation': 'US',
      isAndroid: true,
      isCordovaFromAppStore: true,
      isIOS: false,
      isMobileScreenSize: false,
    },
//    {
//      name: 'ballotMainTest: Samsung Galaxy Tab 4',
//      build: buildNameForDisplay,
//      device: 'Samsung Galaxy Tab 4',
//      os: '',
//      os_version: '4.4',
//      app: browserStackConfig.BROWSERSTACK_APK_URL,
//      browserName: 'Android',
//      browser_version: '',
//      real_mobile: true,
//      acceptSslCerts: true,
//      'browserstack.console': 'info',
//      'browserstack.appium_version': '1.17.0',
//      'browserstack.local': false,
//      'browser.geoLocation': 'US',
//      isAndroid: true,
//      isCordovaFromAppStore: true,
//      isIOS: false,
//      isMobileScreenSize: false,
//    },
  ],
  webviewConnectTimeout: 90000,
  baseUrl: browserStackConfig.WEB_APP_ROOT_URL,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  reporters: ['concise'],

  framework: 'mocha',
  mochaOpts: {
    ui: 'bdd',
    timeout: 360000,
  },
}
