FROM public.ecr.aws/docker/library/node:22 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM public.ecr.aws/nginx/nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
COPY docker/scripts/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]

