// Ballot Constants
module.exports = require('keymirror')({
  VOTER_SUPPORTING_SAVE: null,
  VOTER_STOP_SUPPORTING_SAVE: null,
  VOTER_OPPOSING_SAVE: null,
  VOTER_STOP_OPPOSING_SAVE: null,
  VOTER_STAR_ON_SAVE: null,
  VOTER_STAR_OFF_SAVE: null,
  POSITIONS_RETRIEVED: null,
  CANDIDATE_RETRIEVED: null,
  STAR_STATUS_RETRIEVED: null,
  CANDIDATE_DETAIL_RETRIEVED: null
});
